### ISSUE TITLE
Feature Request: `data.gitlab_group`

### ISSUE THREAD

**Issue by mkjmdski** [terraform-providers/terraform-provider-gitlab#103]
Hi!
I think it would be great if we could import gitlab_group to data source same as we do with gitlab_project. It helps to attach environment variables to the group without getting worried that group could get destroyed by accident.

**Comment by jcmcken** [comment]
Maybe this is a different feature request, but one thing that's annoying right now is you need to hard-code numeric group IDs. It would be nice to use a ``gitlab_group`` data source to look this information up by  (human) group name instead.

**Comment by matejvelikonja** [comment]
@mkjmdski @jcmcken please check PR #129

**Comment by jcmcken** [comment]
Unfortunately, I can't access GitHub from work at the moment, so I won't be able to test this easily. :(
