### ISSUE TITLE
[Feature Request] Project deploy tokens

### ISSUE THREAD

**Issue by mishak87** [terraform-providers/terraform-provider-gitlab#107]
Hello it would be really useful to have resource for creating deploy tokens with scope read_repository and read_registry.

**Comment by laurawadden** [comment]
This feature would also help me a lot.

**Comment by sandhose** [comment]
The deploy tokens are not exposed in the GitLab API right now, but there is a PR currently open for that: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/29864

**Comment by abeluck** [comment]
This is still in progress. The upstream ticket has changed urls, it is now located at :

https://gitlab.com/gitlab-org/gitlab/issues/21811

**Comment by toadjaune** [comment]
The API endpoints are complete and merged (https://gitlab.com/gitlab-org/gitlab/issues/21811), and will be included in this month's release (on 2020-03-22).

So, if someone wants to start working on an implementation, it's possible already !

**Comment by giorgioazzinnaro** [comment]
I have contributed this to the gitlab client lib in xanzy/go-gitlab#802 and am now working on this here: #284 
I thought I'd mention just in case anyone also intended to work on this.
I am still waiting on GitLab to close a couple of bugs on their side however before this is fully functioning..
