### ISSUE TITLE
Broken acceptance tests for project_cluster

### ISSUE THREAD

**Issue by matejvelikonja** [terraform-providers/terraform-provider-gitlab#111]
GitLab 11.9 introduced some changes and because of that `project_cluster` acceptance tests fail.

Looks like GitLab is validating `kubernetes_ca_cert` field. In the acceptance test a non valid pem certificate is given.

### Terraform Version
All

### Affected Resource(s)
- project_cluster

### Debug Output
```
--- FAIL: TestAccGitlabProjectCluster_basic (7.06s)
    testing.go:538: Step 1 error: Error applying: 1 error(s) occurred:

        * gitlab_project_cluster.foo: 1 error(s) occurred:

        * gitlab_project_cluster.foo: PUT http://127.0.0.1:8080/api/v4/projects/7/clusters/2: 400 {message: {platform_kubernetes.ca_cert: [must be a valid PEM certificate]}}
```

### Expected Behavior
Acceptance tests should pass.

### Actual Behavior
Acceptance test `TestAccGitlabProjectCluster_basic` fails with error `must be a valid PEM certificate`.

### Steps to Reproduce
Run `make testacc`

### References
- https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_cluster_test.go#L44
- https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_cluster_test.go#L59

**Comment by matejvelikonja** [comment]
I can fix this issue, since I've added this code. But I would like to know how to tackle this properly.

We have 2 options:
- add a real `pem` certificate to acceptance test and commit it to code
- generate `pem` certificate in the test itself, probably with Terraform

First option needs a commited certificate in the code, which could fail with some security checks.  
Second option needs a new Terrform provider in the tests.

Maybe there's another option. Any ideas?

**Comment by roidelapluie** [comment]
commit a fake pem.
