### ISSUE TITLE
Support for masked variables (gitlab_project_variable)

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-gitlab#117]
Gitlab is currently rolling out a `masked` parameter for variables, which allows controlling whether a project variable is masked in the logs.

More info: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/27236

Would be good to follow suit and add  a `masked` boolean, just like we already have `protected`. (I might work on this patch, no promises)

**Comment by allquantor** [comment]
I will add it in scope of https://github.com/terraform-providers/terraform-provider-gitlab/pull/154
