### ISSUE TITLE
gitlab_group_cluster resource

### ISSUE THREAD

**Issue by sixcorners** [terraform-providers/terraform-provider-gitlab#138]
Please create a gitlab_group_cluster resource to be able to configure a kubernetes cluster at the group level.

**Comment by matejvelikonja** [comment]
GitLab API does not support that, yet.

https://gitlab.com/gitlab-org/gitlab-ce/issues/55623

**Comment by sixcorners** [comment]
Looks like support was added.

**Comment by sixcorners** [comment]
So if I were to implement this would it be fine to just essentially copy all of the stuff from gitlab_project_cluster? That seems to be how the other group stuff was made.

**Comment by magic7s** [comment]
This would be awesome to have.
https://docs.gitlab.com/ee/api/group_clusters.html
