### ISSUE TITLE
[Feature request] Enable archiving of project instead of deletion when specified

### ISSUE THREAD

**Issue by dihedron** [terraform-providers/terraform-provider-gitlab#141]
## Short description
It would be nice if the Gitlab provider gave a way to *archive* an old project instead of always destroying it. 

## Rationale
Destroying a repository is an irreversible operation and Gitlab itself requires special handling such as typing the name of the repo to confirm that you really, *really* want to destroy it since there's no going back.
If you value what's inside a project, archiving it is the safest way of handling its removal; moreover I expect archiving to be *by far* the most common way of removing something, especially in enterprise contexts.

## How to address the issue
It would be nice if a project could be marked with a special attribute (say, "on_delete_archive"), whose default "false" preserves the current destructive behaviour and when explicitly set to true instructs the provider to archive a project that is found missing from the .tf file instead of destroying it forever.
The attribute could be toggled at will without affecting an existing project (it is not stored on the server, it's only in the tfstate); the last value before removing the "gitlab_project" HCL block would determine the provider's behaviour.
***NOTE: I have already implemented this feature, it's extremely simple and works as expected; I still want to run a few additional tests with no haste, and check if some kind of "DiffSuppress" on the new attribute would make the whole behaviour more streamlined, then I'll submit a PR.*** (see https://github.com/dihedron/terraform-provider-gitlab/commit/735e431c560a946b0b582d3d55c773e26cd730f7 )

## Terraform Version
Not an issue: independent of terraform version.

## Affected Resource(s)
Only affected resource is `gitlab_project`

## Terraform Configuration Files
Something like this:
```hcl
provider "gitlab" {
    base_url = "http://localhost/api/v4/"
    token = "<my token>"
}

# missing attribute: defaults to false, deleted (irreversibly destroyed) as usual
resource "gitlab_project" "sample_project_1" {
    name = "example_1"
}                                                                                                                                                                                    

# attribute explicitly set to "true", project archived upon removal
resource "gitlab_project" "sample_project" {
    name = "example_2"
    on_delete_archive = true
}                                                                                                                                                                                    
```

**Comment by roidelapluie** [comment]
I think we would better do it by simply adding an "archived" parameter to the project. That way we also support unarchiving.

**Comment by dihedron** [comment]
I think the `archived` attribute addresses a different use case, which is equally valuable but different.
Explicitly archiving a project is OK and I'm ready to implement it, but it does not save you from inadvertent removal of a valuable asset, which might happen cause people make mistakes. 

The Gitlab product safeguards you from this by requiring that you enter the name of the project for confirmation and then press the button again; direct access to the API does not, so we're removing a fuse somehow.

The point is that Gitlab is a stateful service by definition; the more modern your infrastructure, the more valuable the info you put in there, including things such as your whole infrastructure layout or the most valuable codebase. Then someone in a rush comes in and instead of copy-pasting simply changes the name of an existing project in place... 

Putting in place a knob that allows administrators to safeguard their assets in spite of accidental removals of stanzas in a HCL file has in IMHO some value, the more so when you are managing hundreds of very similar projects. Moreover it has little to no side effects: the only one I can think of is that you will not be able to create a project with the same name, because it's taken.
