### ISSUE TITLE
Update website/gitlab.erb with latest resources & data sources

### ISSUE THREAD

**Issue by ThatGerber** [terraform-providers/terraform-provider-gitlab#149]
Documentation is out of date, in general, but it `website/gitlab.erb` needs to be cleaned up. Two resources are missing and they should probably be sorted in alphabetical order.

### Affected Resource(s)

- gitlab_branch_protection
- gitlab_tag_protection

### References

- https://github.com/terraform-providers/terraform-provider-gitlab/pull/68
- https://github.com/terraform-providers/terraform-provider-gitlab/pull/125

**Comment by roidelapluie** [comment]
done
