### ISSUE TITLE
Support for issues

### ISSUE THREAD

**Issue by lyda** [terraform-providers/terraform-provider-gitlab#152]
A long while ago I worked at a place we'll call the Chocolate Factory. We had a tool like terraform (let's call it Smasher) that would spin up large clusters and generally manage the state and workflow of this sort of work. One thing it did was to file tickets when it needed a human to do things.

Once the ticket was addressed and closed successfully, Smasher would continue running. I'm not quite sure how this might work with terraform since it could end up in states where it filed the ticket and would then need to stop in an unfinished, but complete for now state.

But one part of it would involve supporting creating and getting the state of tickets in gitlab.

**Comment by sudoapt-getclean** [comment]
Hi Lyda,
Nice workflow you had there, If you want to implement this with Terraform you really don't need the provider to create tickets for you.
1. When the Terraform apply fails you can just make an API call to Gitlab to create a  ticket. 
2. After the Ticket is resolved you can make a new plan and do a new Terraform apply.

This ticket has no place in the state and should not be created with a provider.

I have a strong feeling that this provider will be better off if it's documentation and code are not cluttered with options to create objects that have no business in the state file.

Let me know if you disagree!

**Comment by lyda** [comment]
I do disagree, but sadly terraform [looks unlikely][response] to go with this. In both scenarios the idea is to move the workflow out of, well, a workflow manager. I get it. Terraform has a focus on "infrastructure" and tickets are not considered infrastructure.

I must admit though that Smasher did make all this a bit easier and captured the full workflow in its config. Maybe as time goes on there might be a shift and tickets will be seen as part of infrastructure. For now though, I'll close the ticket.

[response]: https://github.com/hashicorp/terraform/issues/17681#issuecomment-503777441
