### ISSUE TITLE
[feature request] support group and project variables of type 'file'

### ISSUE THREAD

**Issue by jimvandervoort** [terraform-providers/terraform-provider-gitlab#153]
GitLab allows settings group and project variables with type 'file'. GitLab CI creates a temporary file with the contents of the variable while the actual env variable gets set to the path to that file. [Gitlab docs](https://docs.gitlab.com/ee/ci/variables/#variable-types).

The gitlab API supports file variables for both [groups](https://docs.gitlab.com/ce/api/group_level_variables.html#update-variable) and [projects](https://docs.gitlab.com/ce/api/project_level_variables.html#create-variable).

Can Terraform support this feature? Would very useful :).

**Comment by sudoapt-getclean** [comment]
I like it!
I hadn't seen this feature at all yet in Gitlab but I could use it.
It should be super straightforward to add as long as the upstream library that implements the gitlab api in go has support for it already.
