### ISSUE TITLE
GitLab Premium/Ultimate License for testing?

### ISSUE THREAD

**Issue by ThatGerber** [terraform-providers/terraform-provider-gitlab#157]
I'd like to contribute some of the work that I've done back, but much if it is locked behind the paid versions of GitLab. Without a license, or a user/group with the higher paid versions, we'd be unable to automate the testing of those providers in GitLab. 

Is there a way that GitLab could provide a testing license or other method of testing the paid versions of GitLab so that we can continue to build out the provider? I'd be willing to help reach out to GitLab and find out if there's a way to get a license or key imported into GitHub so that we can at least run the automated tests when PRs are pushed.

Thanks

**Comment by six-arm** [comment]
I'm working on a resource for  project push rules and running into a similar issues.  I've got a paid license I can use for dev/test in my env, but I'm looking for advice on how to contribute.  I'm seeing `make testacc` failures when running against EE for the jira and slack services.  Would like to be able to show these in the travis-ci pipeline.

**Comment by roidelapluie** [comment]
Hello, we will get a 1 year premium license for gitlab to start with.

**Comment by roidelapluie** [comment]
The license is here. I will add it to CI very soon.

**Comment by six-arm** [comment]
@roidelapluie, if there's anything I can do to help please let me know.

**Comment by baurmatt** [comment]
The Gitlab EE license was introduce with #188. Is there anything else we need to do here or can this issue be closed?

**Comment by roidelapluie** [comment]
yeah that's fine ;)
