### ISSUE TITLE
Feature Request: Group Runner Token

### ISSUE THREAD

**Issue by guhcampos** [terraform-providers/terraform-provider-gitlab#181]
### Use Case

The provider already exposes project-wide runner tokens, which has limited usefulness on an organization level. Most non-oss teams have multiple projects in Gitlab, including subgroups and what not, and it's common to register Gitlab Runners for the top group so they are available to all projects. This is a fairly common use case for the Kubernetes Gitlab Runner.

To enable this, the runner token for the group needs to be exposed by the `gitlab_group` resource and data source, so it can be piped into other Terraform resources such as `helm_release`.

**Comment by sudoapt-getclean** [comment]
Great idea, and use-case.
I've requested this field in supporting library so that we can implement it for group and project(already supported) at the same time.

**Comment by jrdelarosa8** [comment]
I've submitted PR to xanzy/go-gitlab, which aims to address exposing the group runners_token attribute. If a maintainer can assign this issue to me, I'd be happy to help add the feature.
