### ISSUE TITLE
[Feature Request]: LDAP synchronisation functionality 

### ISSUE THREAD

**Issue by mdaalman** [terraform-providers/terraform-provider-gitlab#183]
Hello

We would like to have the “LDAP Synchronisation" functionality for groups added to the Gitlab provider. 

Is it possible to add this feature?

Thanks,

**Comment by kikitux** [comment]
this was impkemented and merged by https://github.com/terraform-providers/terraform-provider-gitlab/pull/296
released as 2.8.0
