### ISSUE TITLE
Error importing user from gitlab to terraform resource

### ISSUE THREAD

**Issue by Procras** [terraform-providers/terraform-provider-gitlab#193]
### Terraform Version
Terraform v0.12.10
+ provider.gitlab v2.3.0

### Affected Resource(s)
- gitlab_user 

### Terraform Configuration Files
```hcl
# Configure the GitLab Provider
provider "gitlab" {
  token    = "${var.gitlab_token}"
  base_url = "https://localhost/gitlab"
  insecure = true
}

resource "gitlab_user" "user" {
  name             = "firstname lastname"
  username         = "user"
  password         = "minimum8"
  email            = "email@email.io"
  projects_limit   = 100000
  can_create_group = true
}
```

### Debug Output
None

### Panic Output
None

### Expected Behavior
Terraform plan should output no changes

### Actual Behavior
Terraform wants to force email replacement on current user

```hcl
  # gitlab_user.user must be replaced
-/+ resource "gitlab_user" "user" {
        can_create_group  = true
      + email             = "email@email.io" # forces replacement
      ~ id                = "25" -> (known after apply)
      + is_admin          = false
      + is_external       = false
        name              = "firstname lastname"
      + password          = (sensitive value)
        projects_limit    = 100000
      + skip_confirmation = true
        username          = "user"
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create new user in gitlab
2. Create resource representing user in a  .tf
3. `terraform import gitlab_user <user_id>`
4. `terraform fmt && terraform validate && terraform plan`

### Important Factoids
No

### References
None

**Comment by mnology** [comment]
It should be noted that `terraform import` appears to create the user in the state with `email: null`. Importing with null will mean that imported user resources will always have to be recreated due to perceived email attribute changes.

I've been able to tweak the state manually to fix the email attr in order to get a sensible plan in a test environment, but this isn't feasible for most cases.

**Comment by deweysasser** [comment]
Does this generate any interest from a developer?  The issue renders the gitlab provider substantially problematical to use.
