### ISSUE TITLE
[Documentation] Rename roles "master" to "maintainer"

### ISSUE THREAD

**Issue by Andor** [terraform-providers/terraform-provider-gitlab#198]
According to [GitLab documentation](https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions): `Note: In GitLab 11.0, the Master role was renamed to Maintainer`. So I guess we need to update documentation and cover that roles renaming as well.

`gitlab_group_membership` has sentence `access_level - (Required) Acceptable values are: guest, reporter, developer, master, owner.`
`project_membership` has `access_level - (Required) One of five levels of access to the project.`

### Terraform Version
```
Terraform v0.12.12
+ provider.gitlab v2.3.0
```

### Affected Resource(s)
1. [gitlab_group_membership](https://www.terraform.io/docs/providers/gitlab/r/group_membership.html)
1. [project_membership](https://www.terraform.io/docs/providers/gitlab/r/project_membership.html)

### References
https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions

**Comment by roidelapluie** [comment]
fixed in f6ddb682ac8cec3cba914c09d93a10e573b86fb9
