### ISSUE TITLE
Support for option "remove_source_branch_after_merge" for projects

### ISSUE THREAD

**Issue by Andor** [terraform-providers/terraform-provider-gitlab#200]
Since [merge request](https://gitlab.com/gitlab-org/gitlab/merge_requests/18408) is merged GitLab API will have option `force_remove_source_branch` in the API.
It gonna be rather cool to be in touch with fresh changes in GitLab API and support this option.

### Affected Resource(s)
Please list the resources as a list, for example:
- `gitlab_project`

### Terraform Configuration Files
```hcl
resource "gitlab_project" "some-project" {
...
  force_remove_source_branch = true
}
```

### References
https://gitlab.com/gitlab-org/gitlab/issues/18283
https://gitlab.com/gitlab-org/gitlab/merge_requests/18408

**Comment by baurmatt** [comment]
This was introduced with Gitlab 12.5 --> https://about.gitlab.com/blog/2019/11/22/gitlab-12-5-released/#delete-source-branch-once-merged

**Comment by Andor** [comment]
@baurmatt yup

**Comment by baurmatt** [comment]
https://github.com/xanzy/go-gitlab/issues/742 is required before we can implement this in the provider.

**Comment by baurmatt** [comment]
This got implemented by the upstream library and $person could start implementing this.

**Comment by MarcinNowak-codes** [comment]
Consider to stay with the same as GitLab API argument name: 

```
resource "gitlab_project" "some-project" {
...
  remove_source_branch_after_merge = true
}
```

**Comment by apricote** [comment]
The attribute is still missing from the [`Project`](https://github.com/xanzy/go-gitlab/blob/master/projects.go#L40) struct and is not returned when reading the project using `GetProject`.

Without this, we can not read the attribute from Gitlab and write it to local TF state in the `dataSourceGitlabProjectRead` and `resourceGitlabProjectRead` functions.

This means that we are unable to detect any changes made to the field in Gitlab.
