### ISSUE TITLE
Feature Request: Add data source option for gitlab_project_push_rules

### ISSUE THREAD

**Issue by japatterson-heb** [terraform-providers/terraform-provider-gitlab#201]
Hello!

I don't believe this should be classified as a bug, but the way the behavior lines up between Gitlab Cloud, project creation, and Terraform application makes it difficult to manage project_push_rules in the Gitlab Cloud environment.

From what I can tell, newly generated projects in the public Gitlab environment inherit a default push_rule object defined as follows:

```
id | <some_id>
project_id | <some_project_id>
created_at | <some_created_at>
commit_message_regex | ""
commit_message_negative_regex | null
branch_name_regex | null
deny_delete_tag | false
member_check | false
prevent_secrets | false
author_email_regex | ""
file_name_regex | ""
max_file_size | 0
commit_committer_check | null
reject_unsigned_commits | null
```

I'm not an admin of Gitlab Cloud, so I can't confirm the settings, but I've observed this behavior when creating new public projects in my personal space.

So when trying to use both `gitlab_project` and `gitlab_project_push_rules` as resources in a new module you run into this behavior

```
module.sample_project.gitlab_project.this: Creating...
module.sample_project.gitlab_project.this: Creation complete after 2s [id=<some_id>]
module.sample_project.gitlab_project_push_rules.this[0]: Creating...

Error: POST https://gitlab.com/api/v4/projects/<some_id>/push_rule: 422 {error: Project push rule exists}
```

I would like to be able to import preexisting `push_rules` instantiations so the projects that inherit `push_rules` from parent group and admin settings as documented in the [Push Rules Page](https://docs.gitlab.com/ee/push_rules/push_rules.html#enabling-push-rules)
can manage modifications to the project-scoped settings via this provider.

### Terraform Version
```
Terraform v0.12.7
+ provider.gitlab v2.3.0
```

### Affected Resource(s)
- gitlab_project_push_rules

**Comment by LipingSun** [comment]
Getting same issue here. Would like to see this feature implemented soon.

**Comment by costalvaro** [comment]
Same issue here, it'd be great to have this feature!
Thanks in advance. 👍

**Comment by josharrington** [comment]
I ran into this issue as well. It seems that the cloud hosted gitlab creates some default push rules when a new project is created. Since we are unable to import these, I created the following workaround. 

```
resource "null_resource" "software_push_rules" {
  for_each = {
    for s in gitlab_project.software : "${s.id}" => "${s.path}"
  }
  provisioner "local-exec" {
    command = <<COMMAND
      curl -X DELETE -H 'Private-Token: ${var.gitlab_token}' https://gitlab.com/api/v4/projects/${each.key}/push_rule && \
      curl -X POST -H 'Private-Token: ${var.gitlab_token}' -H 'Content-Type: application/json' --data '{"prevent_secrets":true,"commit_message_regex":"^\\[(\\w+\\-\\d+|chore)\\].*"}' https://gitlab.com/api/v4/projects/${each.key}/push_rule
    COMMAND
  }
}
```

The above example sets prevent_secrets and creates a regex to prevent noncompliant commit messages.

**Comment by rhysjtevans** [comment]
I've tried deleting using @josharrington method then creating the rules but it looks like the tf module uses PUT where the gitlab.com api is expecting a POST

**Comment by rhysjtevans** [comment]
As a heads up I also noticed if you curl DELETE then navigate to the gitlab.com settings page they get recreated even if nothing is saved - how annoying!
