### ISSUE TITLE
Masked variable missing in gitlab_group_variable

### ISSUE THREAD

**Issue by janmasarik** [terraform-providers/terraform-provider-gitlab#243]
Hey 👋 , 

The option for setting variable as `masked` is not available in `gitlab_group_variable` -  https://www.terraform.io/docs/providers/gitlab/r/group_variable.html, while it is possible to do in the UI. 

Would it be possible to add this flag to the provider? 🙏

**Comment by matejvelikonja** [comment]
unfortunately not supported in GitLab API.

https://docs.gitlab.com/ee/api/group_level_variables.html#create-variable

**Comment by sirlatrom** [comment]
Related issue on gitlab.com: https://gitlab.com/gitlab-org/gitlab/issues/12421

**Comment by greut** [comment]
It seems it's there now: https://docs.gitlab.com/ee/api/group_level_variables.html#create-variable

**Comment by ringods** [comment]
Support for the `masked` property, contributed by @kirecek in #271 is merged. This code has also been released in v2.7.0 of the provider.
