### ISSUE TITLE
Gitlab introduced soft delete of projects and groups

### ISSUE THREAD

**Issue by ringods** [terraform-providers/terraform-provider-gitlab#263]
### Affected Resource(s)
Please list the resources as a list, for example:
- `gitlab_group`
- `gitlab_project`
- the acceptance tests

### Expected Behavior
Removing the block for a `gitlab_group` or `gitlab_project` should delete the resource.

### Actual Behavior
Depending on the subscription tier you are on, the deletion of the resource is either hard or soft version.

A delete is a soft-delete when you are working against:
* Gitlab.com: Silver or Gold
* Self-managed: Premium or Ultimate

As a user, when I delete a `gitlab_project` resource in my code and `tf apply`, the project becomes soft-deleted. If I re-add again within the "pending deletion" period and `tf apply`, the creation will fail because the project is actually still there.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-259
- [Prevent accidental deletions via soft delete for groups](https://gitlab.com/gitlab-org/gitlab/issues/33257)
- [Preventing accidental project deletion via soft delete](https://gitlab.com/gitlab-org/gitlab/issues/32935)
- [Default deletion adjourned period](https://docs.gitlab.com/ee/user/admin_area/settings/visibility_and_access_controls.html#default-deletion-adjourned-period-premium-only)
- https://travis-ci.com/pulumi/pulumi-gitlab/builds/142654401#L1345

**Comment by nagyv** [comment]
I'd recommend setting the default deletion adjourned period in this case to immediate. 

The basic idea of Terraform is that every infrastructure management happens through Terraform, thus soft-delete should be either managed by Terraform or it should be switched off on the infrastructure side. As Terraform does not support soft-delete, the only option is to switch it off.

**Comment by ringods** [comment]
@nagyv as a Gitlab.com user, I can't turn this off when on higher pricing tiers, can I?

**Comment by YusDyr** [comment]
> I'd recommend setting the default deletion adjourned period in this case to immediate.
> 
It's just a ridiculous. Unless we could set up soft/hard delete on project/group level, you can't just propose to turn it off for a whole gitlab. Absolutetly clear there are many teams which work in one gitlab but different projects/groups and not all managed by terraform.

What I'm proposing to do is to add code checking "marked_for_deletion" as this is the only attribute which I seem to be returned in GET /project after delete it. It should be pretty simple, doesn't it?

**Comment by kuahyeow** [comment]
@ringods I am familiar with how GitLab API works but _not_ how Terraform works. 

It looks like the change is that projects and groups changed from being deleted immediately to having a 7 days delay. 

I note that we do emit the `marked_for_deletion_at` field for a project pending deletion. Is it possible to use this field at all ?

**Comment by ringods** [comment]
@kuahyeow this provider pulls in the Go implementation of the Gitlab API from another project. Can you tell me if this change is sufficient to detect a pending delete?

https://github.com/xanzy/go-gitlab/pull/791/files
