### ISSUE TITLE
Add support for certificate-based authorization

### ISSUE THREAD

**Issue by binlab** [terraform-providers/terraform-provider-gitlab#275]
Hi there,

Do you have some plans to add support for certificate-based authorization? Like in the Vault provider for example:
https://www.terraform.io/docs/providers/vault/index.html#cert_file
https://www.terraform.io/docs/providers/vault/index.html#key_file

### Terraform Version
Terraform v0.12.20

### Expected Behavior
Support for client certificate and key

### Actual Behavior
Does not support yet

**Comment by ringods** [comment]
@binlab Support for connecting with custom certificates was contributed in #315 and released today in v2.8.0 of the provider. Is this what wanted?

**Comment by binlab** [comment]
yes, exactly! Thanks!
