### ISSUE TITLE
Document how to have acceptance tests only for Gitlab Enterprise

### ISSUE THREAD

**Issue by ringods** [terraform-providers/terraform-provider-gitlab#314]
Some Gitlab features are only available in Gitlab Enterprise.

### Expected Behavior
Some tests should only run in the `acceptance-ee` test suite, so against a Gitlab Enterprise setup.

### Actual Behavior
All acceptance tests run against both the Community edition and the Enterprise Edition

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #311

**Comment by roidelapluie** [comment]
We have that already

**Comment by roidelapluie** [comment]
`
SkipFunc: isRunningInCE
`

**Comment by ringods** [comment]
@roidelapluie leave this issue open plz. I'll create a PR against this to more clearly document this feature for contributors.

**Comment by roidelapluie** [comment]
The function should also be moved out of the push rules file to a more common and discoverable file.
