### ISSUE TITLE
Slack Notification Services API

### ISSUE THREAD

**Issue by rawkode** [terraform-providers/terraform-provider-gitlab#32]
It would be awesome if we could configure the Slack Notifications integration for projects

**Comment by rawkode** [comment]
I started putting a PR together for this functionality and I've gotten to the stage that I realise this isn't done, probably, because `go-gitlab` doesn't support the `GET` requests :smile: 

I'll head over to their project and get the PR ready

**Comment by rawkode** [comment]
Pending: https://github.com/xanzy/go-gitlab/pull/222

**Comment by gaui** [comment]
Yes please!

**Comment by jorcau** [comment]
@roidelapluie This one can be closed thanks to https://github.com/terraform-providers/terraform-provider-gitlab/pull/96
