### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by hauleth** [terraform-providers/terraform-provider-gitlab#33]
As most of updates are backwards compatible I think it would be useful to release 0.1.1 to allow others to test new features "live".

**Comment by roidelapluie** [comment]
Yes but that would be 0.2.0 due to going to v4 and other breakages in CHANGELOG

**Comment by roidelapluie** [comment]
waiting for #34

**Comment by roidelapluie** [comment]
1.0.0 is out
