### ISSUE TITLE
Gitlab Provider Variable Scope Issue

### ISSUE THREAD

**Issue by rpfinneran** [terraform-providers/terraform-provider-gitlab#347]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.26

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project_variable

### Terraform Configuration Files
```hcl
provider "gitlab" {
    token = "Ez3MU7wCb9ceYPksLT56"
    base_url = "http://52.138.87.206/api/v4/"
    insecure = true
}

variable "project-id" {
   default = 1
}

resource "gitlab_project_variable" "var1" {
   project   = var.project-id
   key       = "TF_VAR_envlocation"
   value     = "West US"
   protected = false
   environment_scope = "staging"
}

resource "gitlab_project_variable" "var2" {
   project   = var.project-id
   key       = "TF_VAR_envlocation"
   value     = "East US"
   protected = false
   environment_scope = "production"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: 
https://gist.github.com/rpfinneran/7c9a2f040555621a58479d3380fd17ce

### Panic Output
N/A

### Expected Behavior
Creates two environment variables in GitLab with same name, but different environment scopes. This works fine (can see both variables with appropriate environment_scope within GitLab.

### Actual Behavior
While the variables are correctly created, the TFSTATE file shows both with same environment_scope. Thus, subsequent terraform actions (apply, destroy, etc) appear to succeed but in reality only alter the state of a single variable. Unfortunately this can be devastating in production CI/CD environments.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. 'terraform destroy'

A variable will remain in the GitLab CI variables.

### Important Factoids
Tested on GitLab CE instance freshly created in Azure. Simply deployed and created secure access token for Terraform provider.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH Pull #346 is similar, updates documentation for environment scope to be correct.

**Comment by rpfinneran** [comment]
You can see this in the TRACE gist...

2020/06/23 16:26:22 [WARN] Provider "registry.terraform.io/-/gitlab" produced an unexpected new value for gitlab_project_variable.var1, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .environment_scope: was cty.StringVal("staging"), but now cty.StringVal("production")
      - .value: inconsistent values for sensitive attribute

**Comment by EmilioEduardo** [comment]
We have the same issue here. This behavior would be used to toggle between deployment environments without having to change var names on deploy scripts. Not possible anymore...

**Comment by jigfox** [comment]
https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_variable.go#L88

I believe this is the line responsible, because the `environment_scope` is not part of the unique id for this resource

**Comment by jigfox** [comment]
https://github.com/terraform-providers/terraform-provider-gitlab/pull/324/files

**Comment by rpfinneran** [comment]
Good catch, closing to #324
