### ISSUE TITLE
Expose gitlab_group ID number or have parent_id accept a string

### ISSUE THREAD

**Issue by WileESpaghetti** [terraform-providers/terraform-provider-gitlab#44]
I can not create subgroups easily. Right now I have to:
1. create the parent group
2. look up the new group's numeric ID
3. hard code the ID into each subgroup's `parent_id` field

### Terraform Version
```
Terraform v0.11.3
+ provider.gitlab v1.0.0
```

### Affected Resource(s)
- gitlab_group

### Terraform Configuration Files
```hcl
provider "gitlab" {
    token    = "**********"
    base_url = "https://gitlab.example.com/api/v4/"
    insecure = "true"
}

resource "gitlab_group" "myParent" {
  name                   = "My Parent"
  path                   = "my-parent"
  visibility_level       = "internal"
  request_access_enabled = "false"
}

resource "gitlab_group" "myChild" {
  name                   = "My Child"
  path                   = "myChild"
  visibility_level       = "internal"
  request_access_enabled = "true"
  parent_id              = "${gitlab_group.myParent.id}"
}

```

### Expected Behavior
The numeric id of `myParent` should be available as an output so that `myChild` gets created as a subgroup of `myParent`

### Actual Behavior
`myParent.id` is a string instead of an integer

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Using a local gitlab-ce omnibus install

**Comment by pdecat** [comment]
Hi @WileESpaghetti, did you import the parent group using its name instead of its numerical ID?

**Comment by WileESpaghetti** [comment]
I created the parent directly using terraform. It wasn't on my server initially

**Comment by pdecat** [comment]
Strange, so far we only met this issue with one imported gitlab group.

**Comment by danielhoherd** [comment]
FWIW I used the "Terraform Configuration Files" section of the original ticket as a model for creating groups and sub groups in gitlab.com and it works fine. Terraform v0.11.8 from docker hashicorp/terraform:light

**Comment by WileESpaghetti** [comment]
I tested the sample code again. I started clean by downloading a fresh copy of Terraform and updated Gitlab to the latest version. I removed the `.terraform` folder and reran `terraform init`. Everything worked when applied.

Terraform information
```
Terraform v0.11.10
+ provider.gitlab v1.0.0
```

Gitlab Info
```
Components
GitLab 11.5.0 (b7b1e8e)
GitLab Shell 8.4.1
GitLab Workhorse v7.1.0
GitLab API v4
Ruby 2.4.5p335
Rails 4.2.10
postgresql 9.6.8
Gitaly Servers
```
