### ISSUE TITLE
Allow to connect a GitLab project to a Kubernetes Cluster

### ISSUE THREAD

**Issue by tmaier** [terraform-providers/terraform-provider-gitlab#46]
https://gitlab.com/help/user/project/clusters/index

A Gitlab project can be connected to a Kubernetes cluster.

It would be great if this configuration can be managed by Terraform.

**Comment by matejvelikonja** [comment]
I will start implementing this in the following days.
PR for the library is already pending https://github.com/xanzy/go-gitlab/pull/556

**Comment by matejvelikonja** [comment]
@roidelapluie @jorcau what do you think?

**Comment by matejvelikonja** [comment]
I guess this issue can be closed, since #87 and #91 have been merged
