### ISSUE TITLE
Allow to set/manage GitLab CI Secret Variables

### ISSUE THREAD

**Issue by tmaier** [terraform-providers/terraform-provider-gitlab#47]
GitLab allows to set Secret Variables via the UI.
https://gitlab.com/help/ci/variables/README#secret-variables

It would be great if Terraform would allow to manage them.

**Comment by tmaier** [comment]
GitLab has REST APIs to manage APIs on [project-level](https://docs.gitlab.com/ee/api/project_level_variables.html) and on [group-level](https://docs.gitlab.com/ee/api/group_level_variables.html)

**Comment by mishak87** [comment]
I need it too. I will try to prototype it.

**Comment by mishak87** [comment]
It is already tracked in #1 as build variables.

@tmaier Please close this issue.

**Comment by armsnyder** [comment]
Is this different from the `gitlab_project_variable` and `gitlab_group_variable` resources in the current version, or can this issue be closed?

**Comment by tmaier** [comment]
@armsnyder Yes, it seems to provide this feature. I am closing this issue. Can you also have a look at #1, as it seems to be related to this topic.
