### ISSUE TITLE
Support archived key on gitlab_project

### ISSUE THREAD

**Issue by zoidbergwill** [terraform-providers/terraform-provider-gitlab#67]
Similar to [github_repository](https://github.com/terraform-providers/terraform-provider-github/blob/master/github/resource_github_repository.go#L96-L100)

I thought it'd be as simple as adding it to the [Schema](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project.go#L24), but archiving a project in Gitlab is a separate API endpoint [here](https://docs.gitlab.com/ee/api/projects.html#archive-a-project)

**Comment by matejvelikonja** [comment]
solved in https://github.com/terraform-providers/terraform-provider-gitlab/pull/148

**Comment by baurmatt** [comment]
@roidelapluie Could you please close this issue? :)
