### ISSUE TITLE
Annoying typo in gitlab_project

### ISSUE THREAD

**Issue by jsirex** [terraform-providers/terraform-provider-gitlab#71]
https://github.com/terraform-providers/terraform-provider-gitlab/blob/v1.0.0/gitlab/resource_gitlab_project.go#L184-L186

**Comment by roidelapluie** [comment]
can you fix it?

**Comment by jsirex** [comment]
I can do it blindly, but not sure it is right way. Also we need a create target branch for 1.x, don't we?

Looks like all new changes are waiting terraform 0.12 release. But for that typo is better to backport it to 1.x and release under 1.0.1 or so.

Or you're going then release all stuff between v1.0.0..master as 1.1.0?

**Comment by roidelapluie** [comment]
I do not think that we need terraform 0.12.

**Comment by jsirex** [comment]
If it doesn't require new terraform then it can be closed as in master is fixed. 

Still waiting for the release, as last release according to github: Oct 6, 2017 :(
