### ISSUE TITLE
Terraform validate does not treat `token` as optional

### ISSUE THREAD

**Issue by awmottaz** [terraform-providers/terraform-provider-gitlab#81]
### Terraform Version

```
Terraform v0.11.10
provider.gitlab v1.1.0
```

### Affected Resource(s)

Gitlab provider

### Terraform Configuration Files

```hcl
provider "gitlab" {
  version = "~> 1.1"
  base_url = "https://foo.custom.gitlab.com"
}
```

### Debug Output

```
$ terraform validate

Error: provider.gitlab: "token": required field is not set
```

### Expected Behavior

No error

### Actual Behavior

Got an error that the token is required

### Important Factoids

According to the [docs](https://www.terraform.io/docs/providers/gitlab/), it should be sufficient to define an environment variable `GITLAB_TOKEN`

**Comment by jorcau** [comment]
Just tested it and it's working for me! Are you sure you ran ```export GITLAB_TOKEN={YOUR_TOKEN}``` before running terraform?

Alternatively you could try running ```GITLAB_TOKEN={YOUR_TOKEN} terraform validate```.

**Comment by awmottaz** [comment]
Thank you! Yes, that works.
