### ISSUE TITLE
Gitlab provider page issue with group resources in sidebar

### ISSUE THREAD

**Issue by sarcasticadmin** [terraform-providers/terraform-provider-gitlab#94]
### Affected Resource(s)
Provider web pages for gitlab resources:  https://www.terraform.io/docs/providers/gitlab/r/group.html#

![screen shot 2019-02-25 at 4 10 02 pm](https://user-images.githubusercontent.com/30531572/53378143-7025c580-3919-11e9-8857-f226fcfa4b09.png)

It looks like `gitlab_group` is defined 3 times in the sidebar instead of  `gitlab_group`, `gitlab_group_membership`, and `gitlab_group_variable`.

Im not sure whats wrong after briefly looking at the `website` dir I couldnt really see anything obvious that would have caused the issue: https://github.com/terraform-providers/terraform-provider-gitlab/tree/master/website

I figured Id let the team know.

### Expected Behavior
Three diffreent sections in the sidebar: `gitlab_group`, `gitlab_group_membership`, and `gitlab_group_variable`

### Actual Behavior
`gitlab_group` is defined 3 times in the sidebar

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Navigate to https://www.terraform.io/docs/providers/gitlab/r/group.html#
2. Look at the sidebar

**Comment by roidelapluie** [comment]
This is already fixed in master.

**Comment by sarcasticadmin** [comment]
Thanks @roidelapluie I must have missed the commit in the history but glad it’s already fixed!

**Comment by roidelapluie** [comment]
thanks to your comment we also updated the website now.
